options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _TF_VERSION: "1.6.6"

steps:

# Terraform Init
- name: hashicorp/terraform:${_TF_VERSION}
  id: Terraform Init
  dir: 'terraform'
  entrypoint: sh
  args:
    - -c
    - |
      terraform init

# Terraform Validate
- name: hashicorp/terraform:${_TF_VERSION}
  id: Terraform Validate
  dir: 'terraform'
  entrypoint: sh
  args:
    - -c
    - |
      terraform validate

# Terraform Plan
- name: hashicorp/terraform:${_TF_VERSION}
  id: Terraform Plan
  dir: 'terraform'
  entrypoint: sh
  args:
    - -c
    - |
      terraform plan -out=tfplan

# Manual Approval
- name: gcr.io/cloud-builders/gcloud
  id: Manual Approval
  dir: 'terraform'
  entrypoint: bash
  args:
    - -c
    - |
      echo "Waiting for manual approval before apply..."
  waitFor: ['Terraform Plan']
  #approval: true

# Terraform Apply
- name: hashicorp/terraform:${_TF_VERSION}
  id: Terraform Apply
  dir: 'terraform'
  entrypoint: sh
  args:
    - -c
    - |
      terraform apply -auto-approve tfplan
  waitFor: ['Manual Approval']